### ISSUE TITLE
0.2.0发版需求

### ISSUE THREAD

**Issue by andy0808** [madmachineio/MadMachineIDE#20]
哈啰 @2ndream 最新的发版需求如下:

1. 审核并合并PR #19 
2. mm-sdk更新至[alpha.7](https://github.com/madmachineio/mm-sdk/releases/tag/v0.2.0-alpha.7)
3. 内置Examples(安装时拷贝到`~/Documents/MadMachine`, 位于`resources/project/Examples`)更新为[MadExamples](https://github.com/madmachineio/MadExamples.git)
4. 取消安装时拷贝`resources/project/Library`
5. IDE现在的Examples页面不能正常显示内置Example, 因为现在的项目名称统一固定为`Package.mmp`, 真实名称需要在项目目录执行`mm-sdk/usr/mm/mm run -a get-name`才能得到, 是否可以修复此问题?
6. Logo更新

**Comment by 2ndream** [comment]
1. done
2. done
3. done, 暂时按主分支最新commit集成，后续必要的话通过github release
4. done
5. done
6. logo随时自助更换😄

**Comment by andy0808** [comment]
完美 : )
