### ISSUE TITLE
Search function in the editor overlap with code content

### ISSUE THREAD

**Issue by andy0808** [madmachineio/MadMachineIDE#7]
**Describe the bug**
Search function in the editor overlap with code content

**To Reproduce**
1. Open any project in MadMachine IDE
2. Open any file in the editor
3. Press `command + f`

**Expected behavior**
The content sould avoid to be overlaped with search content

**Comment by hodovani** [comment]
Hi @andy0808. Thanks for the issue report.

A search bar cover a first line by default. We can find a live example [here](https://codemirror.net/demo/search.html)

![image](https://user-images.githubusercontent.com/12833067/95356363-3ecff280-08cf-11eb-8584-a63e0718f95b.png)

The screenshot below shows how it is now:

![image](https://user-images.githubusercontent.com/12833067/95357204-404dea80-08d0-11eb-96d7-8c18398e4293.png)

Would it be okay if we have the search bar like this:

![image](https://user-images.githubusercontent.com/12833067/95357333-67a4b780-08d0-11eb-87e0-fa9554241305.png)

**Comment by andy0808** [comment]
Hi @hodovani , the second screenshot is OK.

Thanks : )
